name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LATEST_IMAGE: ${{ vars.IMAGE_BASE }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test docker run
        run: |
          docker run --rm ${{ env.LATEST_IMAGE }} -h
      - name: Build and Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ vars.IMAGE_BASE }}:buildcache
          cache-to: type=registry,ref=${{ vars.IMAGE_BASE }}:buildcache,mode=max
          tags: |
            ${{ env.LATEST_IMAGE }}
